package com.renew.survey.response.sync

data class AssignedSurvey(
    val aadhar_card: String,
    val annual_family_income: String,
    val app_unique_code: String,
    val banficary_name: String,
    val electricity_connection_available: String,
    val family_size: String,
    val gender: String,
    val house_type: String,
    val is_cow_dung: String,
    val is_lpg_using: String,
    val mobile_number: String,
    val mst_district_id: String,
    val mst_panchayat_id: String?,
    val mst_state_id: String,
    val mst_tehsil_id: String,
    val mst_village_id: String,
    val next_form_id: String,
    val no_of_cattles_own: String,
    val no_of_cow_dung_per_day: String,
    val no_of_cylinder_per_year: String,
    var device_serial_number: String,
    val parent_survey_id: String,
    val reason: String,
    val system_approval: String,
    val tbl_project_survey_common_data_id: String,
    val tbl_projects_id: String,
    val willing_to_contribute_clean_cooking: String,
    val wood_use_per_day_in_kg: String,
    var family_member_below_15_year: String?,
    var family_member_above_15_year: String?,
    var date_and_time_of_visit: String? = "",
    var did_the_met_person_allowed_for_data : String?,
    var gps_location : String?,
    var do_you_have_aadhar_card: String,
    var font_photo_of_aadar_card: String,
    var back_photo_of_aadhar_card: String,
    var total_electricity_bill: String,
    var frequency_of_bill_payment: String,
    var photo_of_bill: String,
    var cost_of_lpg_cyliner: String,
    var do_you_have_ration_or_aadhar: String,
    var farmland_is_owned_by_benficary: String,
    var if_5m_area_is_available_near_by: String,

    var farmer_unique_id:Int?,
    var alternate_mobile_number : String,
    var residential_address: String,
    var tbl_forms_id:Int?,
    var answer_id:Int?
)