package com.renew.survey.response.sync

data class AssignedSurvey(
    val aadhar_card: String,
    val annual_family_income: String,
    val app_unique_code: String,
    val banficary_name: String,
    val electricity_connection_available: String,
    val family_size: String,
    val gender: String,
    val house_type: String,
    val is_cow_dung: String,
    val is_lpg_using: String,
    val mobile_number: String,
    val mst_district_id: String,
    val mst_panchayat_id: String?,
    val mst_state_id: String,
    val mst_tehsil_id: String,
    val mst_village_id: String,
    val next_form_id: String,
    val no_of_cattles_own: String,
    val no_of_cow_dung_per_day: String,
    val no_of_cylinder_per_year: String,
    val parent_survey_id: String,
    val reason: String,
    val system_approval: String,
    val tbl_project_survey_common_data_id: String,
    val tbl_projects_id: String,
    val willing_to_contribute_clean_cooking: String,
    val wood_use_per_day_in_kg: String,
    var family_member_below_15_year: String?,
    var family_member_above_15_year: String?,
)